### ISSUE TITLE
TypeError: Main.messageTray._notificationWidget is undefined 

### ISSUE THREAD

**Issue by Mastergatto** [ExtraordinaryBen/gnome-shell-extension-taskbar#1]
There's an error in extension.js:1247 :
```javascript
        if ((ShellVersion[1] !== 4) && (ShellVersion[1] !== 16) && (ShellVersion[1] !== 18))
            Main.messageTray._notificationWidget.set_anchor_point(0, this.height);
```
In gnome-shell 3.18 '_notificationWidget' is renamed to 'actor'.

Could this fix be good?
```javascript
        if ((ShellVersion[1] !== 4) && (ShellVersion[1] !== 16))
        {
            Main.messageTray._notificationWidget.set_anchor_point(0, this.height);
        }
        else if (ShellVersion[1] !== 18)
        {
            Main.messageTray.actor.set_anchor_point(0, this.height);
        }
```

**Comment by ExtraordinaryBen** [comment]
So that this piece of code is doing is when the gnome-shell version is not 3,4, 3.16 or 3.18, it will call the set_anchor_point() function. This is fine because _notificationWidget will never get called if one is running 3.18.  (!== means 'not equal,' while === means 'are equal')

**Comment by Mastergatto** [comment]
Thanks, I understand now, because I'm not a coder and I thought this was good. But that doesn't explain why I get this error in Looking Glass, at least without the "fix".

**Comment by ExtraordinaryBen** [comment]
Can you provide a bit more detail as to when LookingGlass is reporting the error? As LookingGlass isn't showing any errors for me. This particular piece of code is related to the bottom panel feature, are you using that by chance?  Maybe it's conflicting with another extension.

**Comment by Mastergatto** [comment]
Sorry, it's my fault! I didn't even realize I had installed GNOME 3.17.92 instead of 3.18.0, and now the extensions looks fine. Looks like that particular version has triggered this issue by not being 3.18 and thus respecting that condition. I'm sorry again for wasting your time!
